### ISSUE TITLE
Motif is able to figure out how to apply your theme automatically

### ISSUE THREAD

**Issue by oleynikd** [erichoracek/Motif#21]
Hi! What exactly does this mean?
Thanks.

**Comment by erichoracek** [comment]
@oleynikd is this the same question as #22 or a separate question?

**Comment by oleynikd** [comment]
No. It is quote from README file. I just wanted to know what exactly you mean by 'automatically'?

**Comment by erichoracek** [comment]
@oleynikd the rest of the sentence reads:

> ...by matching Motif property names to Objective-C property names

This means that when you apply a class from your JSON theme to an object, Motif uses property reflection to introspect the properties on the object's class in the runtime to create a list of its properties. It then iterates through this list of properties, and when it finds a theme property name that matches a class property name, locates the appropriate `NSValueTransformer` subclass to transform the JSON value to a type suitable to be set as the value for the property (NSString → UIEdgeInsets, for example), and then finally sets those properties on objects when able.

However, you still must invoke `applyThemeClass:toObject:` yourself. Does that answer your question?

**Comment by oleynikd** [comment]
Yes, thanks!
It would be great if there were some detailed tutorials...
GREAT WORK!!! THANKS YOU!!!

**Comment by oleynikd** [comment]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: ''UITableView' doesn't have a theme applier for the property 'backgroundColor' or doesn't implement the keypath 'backgroundColor'. You must support one of them.'

Why can't `backgroundColor` be 'automatically' applied to `UITableView` without UITableView+Theming applier?

**Comment by erichoracek** [comment]
@oleynikd `backgroundColor`, while declared as a property on the `UIView` headers, is not actually a property in the runtime. This is due to the following:

> The properties declared in the public headers for UIView aren't actually declared as properties in the source used to build the UIKit, so they're not actually stored as such in the ObjC runtime information in the binary. i.e. there are a bunch of getter/setter methods, and for the public headers they've just added property declarations instead of method declarations for brevity. If they really were properties, they would show up via class_copyPropertyList(), even if they were declared in categories.

From http://stackoverflow.com/questions/848636/objective-c-2-0-class-copypropertylist-how-to-list-properties-from-categorie

**Comment by oleynikd** [comment]
Got it. Thanks.
