### ISSUE TITLE
Chameleon Support ?

### ISSUE THREAD

**Issue by mzekrallah** [erichoracek/Motif#26]
Thanks for the great library ... Any guidance on how this could integrate with Flat Color frameworks like Chameleon ? is it even possible ?

Thanks

**Comment by erichoracek** [comment]
@mzekrallah hmm what exactly do you mean by flat color support? You could just extract the colors from Chameleon and use them in a theme file:

``` javascript
{
    "$FlatColor1": "#123456"
}
```

**Comment by mzekrallah** [comment]
Thank you  .. I meant using the color macros in Chameleon but as you mentioned it could be hardcoded in the style sheet as well .. Thanks
