### ISSUE TITLE
Add Motif.h to podspec

### ISSUE THREAD

**Issue by fcanas** [erichoracek/Motif#4]
Currently `#import <Motif/Motif.h>` doesn't work when using Motif via CocoaPods

**Comment by erichoracek** [comment]
Fixed in https://github.com/erichoracek/Motif/commit/ceb4dfd103f25bc5819f443aa0333f172919ce6a

**Comment by fcanas** [comment]
Ha! Thanks!

I'm integrating this into a project now, so I'll be documenting issues as I can as I go. If I see how to handle them myself, I'll make PRs in the evening/weekend. I was fully expecting to handle this one tonight :)

**Comment by erichoracek** [comment]
Sure thing! Glad to have you testing things out.
