### ISSUE TITLE
Convenience applier categories would be appreciated

### ISSUE THREAD

**Issue by fcanas** [erichoracek/Motif#5]
Support for properties could be included with Motif.

Example transformers from the readme would be really useful if they were default for UIKit classes:

``` objc
+ (void)load
{
    [self
        mtf_registerThemeProperty:@"textColor"
        valueTransformerName:MTFColorFromStringTransformer
        applier:^(UIColor *textColor, UIButton *button) {
            [button setTextColor:textColor forState:UIControlStateNormal];
    }];

    [self
        mtf_registerThemeProperties:@[
            @"fontName",
            @"fontSize"
        ] valueTransformersNamesOrRequiredClasses:@[
            [NSString class],
            [NSNumber class]
        ] applier:^(NSDictionary *properties, UIButton *button) {
            NSString *name = properties[@"fontName"];
            CGFloat size = [properties[@"fontSize"] floatValue];
            button.titleLabel.font = [UIFont fontWithName:name size:size];
        }];
}
```

I can imaging it as an optional subspec in CocoaPods so that it can be more easily platform-specific, and even ignored. I'm not sure what it would look like via Carthage (a separate framework?).

What do you think?

**Comment by fcanas** [comment]
Specifically, `fontName` and `fontSize` aren't properties on `UILabel`.

**Comment by erichoracek** [comment]
@fcanas Most properties will "just work". For example, you'll notice that there's no applier for `contentEdgeInsets`. This is due to the fact that Motif uses reflection to intuit that there's a property named `contentEdgeInsets` on `UIButton` that has a type of `UIEdgeInsets`. It also knows that there's a property on the `.Button` theme class that is named `contentEdgeInsets` and is of type `NSString`. With this knowledge, when the theme class is applied to a `UIButton` it searches for a value transformer that transforms from `NSString` → `UIEdgeInsets`. If there is one, it uses that to apply the value without the consumer ever having to add an property applier.

**Comment by erichoracek** [comment]
@fcanas There are some cases where we can't get this for free though, specifically:
- `UIView.backgroundColor` (while declared as a property, it's on a category, and is thus not queryable via the Objective-C runtime)
- `[UIControl setProperty:forState:]` (for obvious reasons)
- `UIView.layer` properties (there are only a few, so it shouldn't be much work to add them yourself)

**Comment by fcanas** [comment]
What about fonts on buttons, labels, text fields, etc?

I do find so many of the free ones working, which is super nice. But fonts seem like a case that's not KVC on the two typical characteristics that need to change (name, size).

Maybe it's worth specifying a Motif type for fonts, much like for the struct types of colors.

``` json
{
    "$bodyFont" : { "name" : "Helvetica-Neue", "size" : 16 }
}
```

**Comment by erichoracek** [comment]
@fcanas Check out the way that the `Dynamic Theming Example` does typography—it's not the same way as the example in the README. The only applier on `UIButton` is as follows:

``` objective-c
[self
    mtf_registerThemeProperty:ControlsThemeProperties.text
    requiringValueOfClass:MTFThemeClass.class
    applierBlock:^(MTFThemeClass *themeClass, UIButton *button) {
        [themeClass applyToObject:button.titleLabel];
    }];
```

That way, the class for the `UIButton` is:

``` javascript
".Button": {
    "text": ".SubheadText",
    "contentEdgeInsets": "{10.0, 20.0, 10.0, 20.0}",
    "cornerRadius": 5.0
}
```

And the definition of `.SubheadText` is:

``` javascript
"$SubheadFontSize": 16,
"$RegularFontName": "AvenirNext-Regular",
".SubheadText": {
    "fontSize": "$SubheadFontSize",
    "fontName": "$RegularFontName",
    "color": "$HeadingTextColor"
}
```

**Comment by erichoracek** [comment]
I probably should update the README example to do things this way instead, since it seems cleaner :)

**Comment by fcanas** [comment]
- [x] Update readme with text example

**Comment by fcanas** [comment]
At the very least, the readme should use only methods that actually exist ;)

**Comment by erichoracek** [comment]
Haha, which one is out of date?

**Comment by erichoracek** [comment]
Oh, is it `applier` → `applierBlock`?

**Comment by fcanas** [comment]
`+mtf_registerThemeProperties:valueTransformersNamesOrRequiredClasses:applier:`

**Comment by fcanas** [comment]
Transformers → Transformer too, I think. And Property → Properties

**Comment by fcanas** [comment]
I looked it over more carefully, and I think there's an opportunity for improvement of font handling. Either of these, or some combination
- include the UIKit categories from the buttons example, and include any other UIKit classes with prominent need for fonts
- create a font type along the lines of `"{ name : Helvetica-Neue, size : 16 }"` or `"{ $PrimaryFont, 16 }"` with a corresponding `MTFFontFromStringTransformer`

Now that I have appropriate categories in my project, there's no pressing need for this. But it definitely feels like a "batteries not included" situation when the first thing I try and style breaks because fonts are a little different.

I'd be happy to try whichever approach you feel is right.

**Comment by erichoracek** [comment]
I'm somewhat wary of a one-size-fits-all model with fonts. Some people will want to use system Helvetica with `UIFontDescriptors` in which case the only thing to describe their font will be `UIFontTextStyleSubheadline`, `UIFontTextStyleBody`, etc. Others will want to configure custom `UIFonts` with a name and a size. Others won't want to use `UIFonts` directly, but instead will want to use `NSAttributedString` with attributes dictionaries to adjust things like line heights, kernings, etc. Creating a model that supports all of these would have a number of tradeoffs, but allowing users to roll their own enables them to make the model that works best for them.
