### ISSUE TITLE
How to support color with alpha?

### ISSUE THREAD

**Issue by btxkenshin** [erichoracek/Motif#50]
RT
hexstring did not contain alpha,did Motif support color with alpha directly?

**Comment by erichoracek** [comment]
I'd suggest using `rgba()`, matching that of the CSS spec: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba()

Currently the CSS spec does not support hex colors with alpha, but I believe it's coming in CSS color module 4: https://drafts.csswg.org/css-color/#hex-notation

**Comment by btxkenshin** [comment]
@erichoracek 
Got it,Motif is excellent to me, there's many new stuff i did not touched before,
Thanks
