### ISSUE TITLE
Edit theme on the phone

### ISSUE THREAD

**Issue by norman784** [erichoracek/Motif#55]
Its possible to edit the themes on the phone? I've a project that requires that the user can customise some UI elements and will be cool if its possible to do with Motif.

**Comment by erichoracek** [comment]
@norman784 sure—if you create a file within your documents directory (for example) and use that as the theme file, I don't see why you couldn't use a similar construct to the https://github.com/erichoracek/Motif/blob/master/Motif/Core/MTFLiveReloadThemeApplier.h to achieve the results you're interested in.

**Comment by norman784** [comment]
thanks, will play with it then!
