### ISSUE TITLE
Problem with imports in angle brackets

### ISSUE THREAD

**Issue by fabiorodella** [erichoracek/Motif#80]
I installed the latest version of Motif (0.3.1) through cocoapods but I'm seeing the following error when building:

```
.../Pods/Motif/Carthage/Checkouts/libyaml/src/yaml_private.h:6:10: 'yaml.h' file not found with <angled> include; use "quotes" instead
```

This header is marked as Public in the produced framework, should it really be so? (the name seems to indicate otherwise :) )

The same thing also happens with the `config.h` import in the same file. If I change both to quotes as the error message suggests, it works.

**Comment by erichoracek** [comment]
Fixed in #88 / 0.3.3
