### ISSUE TITLE
Allow overriding of existing constants with identical names by registering new constants.

### ISSUE THREAD

**Issue by kunal30xi** [erichoracek/Motif#86]
Great work on the framework. We just started using Motif and really like it. When coming up with internal standards on how best to adopt it we ran into a scenario where we would like the ability to define constants and have the ability to override as needed.

We need the ability to switch colors for a few items at startup depending on a customer preference. 
Our original idea was to use load 2 different themes (lets call it Theme A and Theme B).

Theme A (loads classes and constants from A.json)
Theme B (loads A.json and B.json where B.json contains overrides of constant values)

We were then going to use the MTFDynamicThemeApplier to switch between the two.

We see that the overriding of existing constants and classes is prohibited in the MTFThemeParser and generates a parsing error if attempted. 

We would love the ability to do it (as described in our above scenario) maybe through a configurable property (so as not to impact current users). 

Would y'all be opposed to to this idea? If not, we are happy to submit a pull request for this.

**Comment by erichoracek** [comment]
Hi @kunal30xi—glad you're liking Motif so far.

The recommended way to conditionally override constants is by using a set of "mapping" theme files that redefine the same constant mapped depending on which one is loaded. This practice is documented under [this section](https://github.com/erichoracek/Motif#mapping-themes) in the README.

For an example of this, take a look at the `DarkMappingsTheme.yaml` and `LightMappingThemes.yaml` files in the [example project](https://github.com/erichoracek/Motif/tree/master/Examples/DynamicThemingExample/Themes). As a specific example, `$ContentBackgroundColor` is mapped to either `$WhiteColor` or `$GrayColor`, depending on whether you load your theme hierarchy with `DarkMappingsTheme.yaml` and `LightMappingThemes.yaml`, respectively.

Hope that helps clear things up! Let me know if I misunderstood your question.

**Comment by kunal30xi** [comment]
@erichoracek Thanks for the quick response. Yes we read that section and that is what we ended up going with. 

Other than a potential for error by allowing for re-declaration of constants in theme files, what potential concerns would there be of defining a Theme (with structure and styling) and conditionally loading a 2nd Theme file with overrides?

**Comment by erichoracek** [comment]
I'm generally against the concept of "overrides", since it could cause typos or copy-paste errors to change themes without generating a theme parsing error. Manually creating "mappings" tends to make this less error-prone, since both are unique symbols.

Feel free to re-open if this doesn't answer your question.
