### ISSUE TITLE
Incorrect path to code coverage files when executing test suite

### ISSUE THREAD

**Issue by kunal30xi** [erichoracek/Motif#87]
When we execute our test suite built against Motif, we are seeing the following output: (I'm assuming this is the path to the code coverage files located on your workstation).

`profiling: /Users/erh/Library/Developer/Xcode/DerivedData/Motif-fymrucbnitjyghdhgxaviyllghzs/Build/Intermediates/Motif.build/Release-iphonesimulator/Motif-iOS.build/Objects-normal/x86_64/NSURL+LastPathComponentWithoutExtension.gcda: cannot open: No such file or directory
profiling: /Users/erh/Library/Developer/Xcode/DerivedData/Motif-fymrucbnitjyghdhgxaviyllghzs/Build/Intermediates/Motif.build/Release-iphonesimulator/Motif-iOS.build/Objects-normal/x86_64/NSURL+LastPathComponentWithoutExtension.gcda: cannot open: No such file or directory
profiling: /Users/erh/Library/Developer/Xcode/DerivedData/Motif-fymrucbnitjyghdhgxaviyllghzs/Build/Intermediates/Motif.build/Release-iphonesimulator/Motif-iOS.build/Objects-normal/x86_64/MTFScreenBrightnessThemeApplier.gcda: cannot open: No such file or directory
profiling: /Users/erh/Library/Developer/Xcode/DerivedData/Motif-fymrucbnitjyghdhgxaviyllghzs/Build/Intermediates/Motif.build/Release-iphonesimulator/Motif-iOS.build/Objects-normal/x86_64/MTFScreenBrightnessThemeApplier.gcda: cannot open: No such file or directory`

---- (rest left out in the interest of brevity)

**Comment by erichoracek** [comment]
Hi @kunal30xi — this will likely be fixed when this project is migrated from the old `gcov` format to the new `profdata` format. This was blocked by Slather incompatibility issues, but has likely been fixed now. Will take a look when I get a chance.

**Comment by erichoracek** [comment]
Fixed in #88 / 0.3.3
